api:
  build: api
  command: python runserver.py
  volumes:
   - api/sketchcase:/code/sketchcase
   - api/runserver.py:/code/runserver.py
   - api/setup_db.py:/code/setup_db.py
   - media:/media
  links:
    - rethinkdb

rethinkdb:
  image: rethinkdb
  ports:
   - "28015:28015"
   - "8080:8080"
  volumes:
    - .:/data

nginx:
  image: nginx
  volumes:
   - frontend/static:/web
   - media:/media
   - config/nginx/conf.d:/etc/nginx/conf.d
   - config/nginx/nginx.conf:/etc/nginx/nginx.conf
  ports:
   - "80:80"
  links:
    - api