api:
  build: .
  command: python runserver.py
  ports:
   - "5000:5000"
  volumes:
   - .:/code
  links:
    - rethinkdb

rethinkdb:
  image: rethinkdb
  ports:
   - "28015:28015"
   - "8080:8080"
  volumes:
    - .:/data

nginx:
  image: nginx
  volumes:
   - frontend/static:/web
   - config/nginx:/etc/nginx/conf.d
  ports:
   - "80:80"